//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelancerSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppliedFreelancer
    {
        public string username { get; set; }
        public int postID { get; set; }
        public string proposal { get; set; }
        public int acceptance { get; set; }
        public int Id { get; set; }
    
        public virtual PostsTable PostsTable { get; set; }
    }
}
