//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelancerSystem
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class FreelancerTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FreelancerTable()
        {
            this.AppliedPosts = new HashSet<AppliedPost>();
            this.SavedPosts = new HashSet<SavedPost>();
        }
    
        public string username { get; set; }
        public int role { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<int> post_id { get; set; }
        public string password { get; set; }
        public string photo_id { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppliedPost> AppliedPosts { get; set; }
        public virtual PostsTable PostsTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedPost> SavedPosts { get; set; }
    }
}
