//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelancerSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FreelancerSystemDB : DbContext
    {
        public FreelancerSystemDB()
            : base("name=FreelancerSystemDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTable> AdminTables { get; set; }
        public virtual DbSet<AppliedPost> AppliedPosts { get; set; }
        public virtual DbSet<ClientTable> ClientTables { get; set; }
        public virtual DbSet<FreelancerTable> FreelancerTables { get; set; }
        public virtual DbSet<PostsTable> PostsTables { get; set; }
        public virtual DbSet<SavedPost> SavedPosts { get; set; }
        public virtual DbSet<RegistrationTable> RegistrationTables { get; set; }
        public virtual DbSet<AppliedFreelancer> AppliedFreelancers { get; set; }
    }
}
